/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/bundles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search for bundles */
        get: {
            parameters: {
                query?: {
                    /** @description Search query */
                    q?: string;
                    /** @description Filter by server type */
                    type?: string;
                    sort?: "downloads" | "recent" | "name";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bundles: {
                                name: string;
                                display_name?: string | null;
                                description?: string | null;
                                author?: {
                                    name: string;
                                } | null;
                                latest_version: string;
                                icon?: string | null;
                                server_type?: string | null;
                                tools?: {
                                    name: string;
                                    description?: string;
                                }[];
                                downloads: number;
                                published_at: string | unknown;
                                verified: boolean;
                                provenance?: {
                                    schema_version: string;
                                    provider: string;
                                    repository: string;
                                    sha: string;
                                } | null;
                            }[];
                            total: number;
                            pagination: {
                                limit: number;
                                offset: number;
                                has_more: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get detailed bundle information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            display_name?: string | null;
                            description?: string | null;
                            author?: {
                                name: string;
                            } | null;
                            latest_version: string;
                            icon?: string | null;
                            server_type?: string | null;
                            tools?: {
                                name: string;
                                description?: string;
                            }[];
                            downloads: number;
                            published_at: string | unknown;
                            verified: boolean;
                            provenance?: {
                                schema_version: string;
                                provider: string;
                                repository: string;
                                sha: string;
                            } | null;
                            homepage?: string | null;
                            license?: string | null;
                            versions: {
                                version: string;
                                published_at: string | unknown;
                                downloads: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/badge.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an SVG badge for a bundle (for README embeds) */
        get: {
            parameters: {
                query?: {
                    /** @description Badge type: version (default), downloads, or runtime */
                    type?: "version" | "downloads" | "runtime";
                };
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SVG badge image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/index.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get multi-platform distribution index for a bundle (MCPB Index spec) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            index_version: string;
                            mimeType: string;
                            name: string;
                            version: string;
                            description: string | null;
                            bundles: {
                                mimeType: string | null;
                                digest: string;
                                size: number;
                                platform: {
                                    os: string;
                                    arch: string;
                                };
                                urls: string[];
                            }[];
                            annotations?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all versions of a bundle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            latest: string;
                            versions: {
                                version: string;
                                artifacts_count: number;
                                platforms: {
                                    os: string;
                                    arch: string;
                                }[];
                                published_at: string | unknown;
                                downloads: number;
                                publish_method: string | null;
                                provenance?: {
                                    schema_version: string;
                                    provider: string;
                                    repository: string;
                                    sha: string;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get information about a specific version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    package: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            version: string;
                            published_at: string | unknown;
                            downloads: number;
                            artifacts: {
                                platform: {
                                    os: string;
                                    arch: string;
                                };
                                digest: string;
                                size: number;
                                download_url: string;
                                source_url?: string;
                            }[];
                            manifest: {
                                [key: string]: unknown;
                            };
                            release?: {
                                tag: string | null;
                                url: string | null;
                            };
                            publish_method: string | null;
                            provenance: {
                                schema_version: string;
                                provider: string;
                                repository: string;
                                sha: string;
                            } | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/@{scope}/{package}/versions/{version}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download a specific version of a bundle */
        get: {
            parameters: {
                query?: {
                    /** @description Target OS (darwin, linux, win32, any) */
                    os?: string;
                    /** @description Target arch (x64, arm64, any) */
                    arch?: string;
                };
                header?: never;
                path: {
                    scope: string;
                    package: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url: string;
                            bundle: {
                                name: string;
                                version: string;
                                platform: {
                                    os: string;
                                    arch: string;
                                };
                                sha256: string;
                                size: number;
                            };
                            expires_at?: string;
                        };
                    };
                };
                /** @description Redirect to download URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/announce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Announce a single artifact for a bundle version from a GitHub release (OIDC only). Idempotent - can be called multiple times for different artifacts of the same version. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        version: string;
                        manifest: {
                            [key: string]: unknown;
                        };
                        release_tag: string;
                        /** @default false */
                        prerelease: boolean;
                        artifact: {
                            filename: string;
                            os: string;
                            arch: string;
                            sha256: string;
                            size: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            package: string;
                            version: string;
                            artifact: {
                                os: string;
                                arch: string;
                                filename: string;
                            };
                            total_artifacts: number;
                            /** @enum {string} */
                            status: "created" | "updated";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search for skills */
        get: {
            parameters: {
                query?: {
                    /** @description Search query */
                    q?: string;
                    /** @description Filter by tags (comma-separated) */
                    tags?: string;
                    /** @description Filter by category */
                    category?: string;
                    /** @description Filter by surface (claude-code, claude-api, claude-ai) */
                    surface?: string;
                    sort?: "downloads" | "recent" | "name";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            skills: {
                                name: string;
                                description: string;
                                latest_version: string;
                                tags?: string[];
                                /** @enum {string} */
                                category?: "development" | "writing" | "research" | "consulting" | "data" | "design" | "operations" | "security" | "other";
                                surfaces?: ("claude-code" | "claude-api" | "claude-ai")[];
                                downloads: number;
                                published_at: string;
                                author?: {
                                    name: string;
                                    /** Format: uri */
                                    url?: string;
                                    /** Format: email */
                                    email?: string;
                                };
                            }[];
                            total: number;
                            pagination: {
                                limit: number;
                                offset: number;
                                has_more: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/@{scope}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get detailed skill information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            description: string;
                            latest_version: string;
                            license?: string;
                            compatibility?: string;
                            allowed_tools?: string[];
                            tags?: string[];
                            /** @enum {string} */
                            category?: "development" | "writing" | "research" | "consulting" | "data" | "design" | "operations" | "security" | "other";
                            triggers?: string[];
                            surfaces?: ("claude-code" | "claude-api" | "claude-ai")[];
                            downloads: number;
                            published_at: string;
                            author?: {
                                name: string;
                                /** Format: uri */
                                url?: string;
                                /** Format: email */
                                email?: string;
                            };
                            examples?: {
                                prompt: string;
                                context?: string;
                            }[];
                            versions: {
                                version: string;
                                published_at: string;
                                downloads: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/@{scope}/{name}/badge.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an SVG badge for a skill (for README embeds) */
        get: {
            parameters: {
                query?: {
                    /** @description Badge type: version (default) or downloads */
                    type?: "version" | "downloads";
                };
                header?: never;
                path: {
                    scope: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SVG badge image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/@{scope}/{name}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download the latest version of a skill bundle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url: string;
                            skill: {
                                name: string;
                                version: string;
                                sha256: string;
                                size: number;
                            };
                            expires_at: string;
                        };
                    };
                };
                /** @description Redirect to download URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/@{scope}/{name}/versions/{version}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download a specific version of a skill bundle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    name: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url: string;
                            skill: {
                                name: string;
                                version: string;
                                sha256: string;
                                size: number;
                            };
                            expires_at: string;
                        };
                    };
                };
                /** @description Redirect to download URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/announce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Announce a skill version from a GitHub release (OIDC only). Idempotent - can be called multiple times. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        version: string;
                        skill: {
                            name: string;
                            description: string;
                            license?: string;
                            compatibility?: string;
                            "allowed-tools"?: string;
                            metadata?: {
                                tags?: string[];
                                /** @enum {string} */
                                category?: "development" | "writing" | "research" | "consulting" | "data" | "design" | "operations" | "security" | "other";
                                triggers?: string[];
                                keywords?: string[];
                                surfaces?: ("claude-code" | "claude-api" | "claude-ai")[];
                                author?: {
                                    name: string;
                                    /** Format: uri */
                                    url?: string;
                                    /** Format: email */
                                    email?: string;
                                };
                                version?: string;
                                examples?: {
                                    prompt: string;
                                    context?: string;
                                }[];
                            } & {
                                [key: string]: unknown;
                            };
                        };
                        release_tag: string;
                        /** @default false */
                        prerelease: boolean;
                        artifact: {
                            filename: string;
                            sha256: string;
                            size: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            skill: string;
                            version: string;
                            /** @enum {string} */
                            status: "created" | "exists";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
