/**
 * Type definitions for mpak SDK
 *
 * Types are derived from the OpenAPI schema (generated by openapi-typescript)
 */

import type { paths } from './schema.js';

// =============================================================================
// Helper types for extracting response types from OpenAPI paths
// =============================================================================

/** Extract the JSON response type from a path operation */
type ResponseOf<T> = T extends {
  responses: { 200: { content: { 'application/json': infer R } } };
}
  ? R
  : never;

/** Extract query parameters from a path operation */
type QueryOf<T> = T extends { parameters: { query?: infer Q } } ? Q : never;

// =============================================================================
// Bundle API Types (from /v1/bundles/*)
// =============================================================================

/** Response from GET /v1/bundles/search */
export type BundleSearchResponse = ResponseOf<paths['/v1/bundles/search']['get']>;

/** Response from GET /v1/bundles/@{scope}/{package} */
export type BundleDetailResponse = ResponseOf<paths['/v1/bundles/@{scope}/{package}']['get']>;

/** Response from GET /v1/bundles/@{scope}/{package}/versions */
export type BundleVersionsResponse = ResponseOf<paths['/v1/bundles/@{scope}/{package}/versions']['get']>;

/** Response from GET /v1/bundles/@{scope}/{package}/versions/{version} */
export type BundleVersionResponse = ResponseOf<paths['/v1/bundles/@{scope}/{package}/versions/{version}']['get']>;

/** Response from GET /v1/bundles/@{scope}/{package}/versions/{version}/download */
export type BundleDownloadResponse = ResponseOf<paths['/v1/bundles/@{scope}/{package}/versions/{version}/download']['get']>;

/** Response from GET /v1/bundles/@{scope}/{package}/index.json */
export type BundleIndexResponse = ResponseOf<paths['/v1/bundles/@{scope}/{package}/index.json']['get']>;

/** Query parameters for bundle search */
export type BundleSearchParams = QueryOf<paths['/v1/bundles/search']['get']>;

// Convenience types
export type Bundle = BundleSearchResponse['bundles'][number];
export type BundleDetail = BundleDetailResponse;
export type BundleVersion = BundleVersionsResponse['versions'][number];
export type BundleArtifact = BundleVersionResponse['artifacts'][number];
export type BundleDownloadInfo = BundleDownloadResponse;

// =============================================================================
// Skill API Types (from /v1/skills/*)
// =============================================================================

/** Response from GET /v1/skills/search */
export type SkillSearchResponse = ResponseOf<paths['/v1/skills/search']['get']>;

/** Response from GET /v1/skills/@{scope}/{name} */
export type SkillDetailResponse = ResponseOf<paths['/v1/skills/@{scope}/{name}']['get']>;

/** Response from GET /v1/skills/@{scope}/{name}/download */
export type SkillDownloadResponse = ResponseOf<paths['/v1/skills/@{scope}/{name}/download']['get']>;

/** Query parameters for skill search */
export type SkillSearchParams = QueryOf<paths['/v1/skills/search']['get']>;

// Convenience types
export type Skill = SkillSearchResponse['skills'][number];
export type SkillDetail = SkillDetailResponse;
export type SkillDownloadInfo = SkillDownloadResponse;
export type SkillVersion = SkillDetailResponse['versions'][number];

// =============================================================================
// Common Types
// =============================================================================

/** Platform identifier (os + arch) */
export interface Platform {
  os: string; // darwin, linux, win32, any
  arch: string; // x64, arm64, any
}

/** Pagination info returned by search endpoints */
export interface Pagination {
  limit: number;
  offset: number;
  has_more: boolean;
}

/** Provenance information for verified packages */
export interface Provenance {
  schema_version: string;
  provider: string;
  repository: string;
  sha: string;
}

/** Author information */
export interface Author {
  name: string;
  url?: string;
  email?: string;
}

// =============================================================================
// Client Configuration
// =============================================================================

/**
 * Configuration options for MpakClient
 */
export interface MpakClientConfig {
  /**
   * Base URL for the mpak registry API
   * @default 'https://api.mpak.dev'
   */
  registryUrl?: string;

  /**
   * Request timeout in milliseconds
   * @default 30000
   */
  timeout?: number;
}
